### ISSUE TITLE
Issue when Build docker run -dit --name ol7_19_con -p 1521:1521 --shm-size="1G" ol7_19:latest

### ISSUE THREAD

**Issue by codersidn** [oraclebase/dockerfiles#13]
I create docker under windows. I create image for docker already done but when run docker for create container show error

******************************************************************************
Handle shutdowns. Thu Nov 19 04:57:34 UTC 2020
docker stop --time=30 {container} Thu Nov 19 04:57:34 UTC 2020
******************************************************************************
/u01/scripts/start.sh: line 5: syntax error near unexpected token `$'{\r''
'u01/scripts/start.sh: line 5: `function gracefulshutdown {

I check on start.sh i don't see this token

**Comment by oraclebase** [comment]
My guess is you have somehow done a "UNIX to DOS" conversion of the files, so you have the wrong line endings. Windows uses 13,10 and UNIX/Linux uses 10. As a result, when the start.sh script runs the incorrect line ending are confusing it.

This is likely to be down to the Git client you are using. Most of them convert line ending to the native format by default. If you try doing a "DOS to UNIX" on all the .sh files before doing your build I would expect this to work.

I've never used Docker on Window. My main machine is Windows 10, but I run up a Linux VM and do all Docker stuff in there, as all my Docker stuff at work is Linux based. The reason I suspect this is the problem is because I've seen this type of thing in my Vagrant build also, which I run on Windows, Linux and Mac hosts.
