### ISSUE TITLE
Remote login does not work as sys when using persistent volume

### ISSUE THREAD

**Issue by rshakerov** [oraclebase/dockerfiles#6]
Hi Tim, thanks for the great work! 
I have built and image from your sources and created container for Oracle 19.

I tried this option from you Docker file examples:

# Persistent storage and part of Docker network called "my_network".
# docker run -dit --name ol8_19_con -p 1521:1521 -p 5500:5500 --shm-size="1G" --network=my_network -v /u01/volumes/ol8_19_con_u02/:/u02 ol8_19:latest

Everything worked fine except one issue: I could not connect as sys from my host. After doing some  checks I found that password file is mapped via link to the file in the config directory on the host. And ls command reported that password file was owned by root. Also V$PWFILE_USERS contained no rows. 
After removing and creating password file in the container I could connect from the host and found one record for the sys user in the V$PWFILE_USERS view.  Looks like some specifics of the Docker running on Windows 10 Pro. 
By the way chown reported no issues when I tried to change owner to oracle:dba but ls still dispalyed root as an owner of the directories mapped to the volume on the host. Also alert.log has some issuse with writing diagnostic info due to the same cause.

Regards, Renat.

**Comment by oraclebase** [comment]
Hi.

As you suspect, this is caused by the discrepancy between the owner outside of the container not matching that of inside. To solve this issue I usually make a group and user on the host that matches that inside the container, as explained here.

https://oracle-base.com/articles/linux/docker-host-file-system-permissions-for-container-persistent-host-volumes

It's a rather clumsy solution, but then mounting external files into Docker is a clumsy solution. :)

Cheers

Tim...

**Comment by rshakerov** [comment]
Hi Tim, seems like you have an article for any case :-) I need to learn your site better. Thanks a lot for the hint. I will check it out.

Regards, Renat.

**Comment by oraclebase** [comment]
I'm still a beginner at Docker. Just enjoy playing... :)
